/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ProdutoDAO;
import controller.ProdutoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import util.Validador;

/**
 *
 * @author sunse
 */
public final class CadastroProduto extends javax.swing.JFrame {
    
    private String modoTela = "";
    public int codProduto;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Cadastro de Produtos");
        
        DesabilitarFormulario();
        BordasTransparentes();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        vlrUnitarioLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        descricaoTxt = new javax.swing.JTextField();
        vlrUnitarioTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tamanhoLabel = new javax.swing.JLabel();
        tamanhoComboBox = new javax.swing.JComboBox<>();
        corLabel = new javax.swing.JLabel();
        corComboBox = new javax.swing.JComboBox<>();
        generoLabel = new javax.swing.JLabel();
        femRadioButton = new javax.swing.JRadioButton();
        mascRadioButton = new javax.swing.JRadioButton();
        quantidadeLabel = new javax.swing.JLabel();
        quantidadeTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deleteButtpn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pesquisarLabel = new javax.swing.JLabel();
        pesquisarTxt = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        vlrUnitarioLabel.setText("VALOR UNITÁRIO:");

        descricaoLabel.setText("DESCRIÇÃO:");

        jLabel10.setText("R$");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADICIONAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tamanhoLabel.setText("TAMANHO:");

        tamanhoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "PP", "P", "M", "G", "GG" }));

        corLabel.setText("COR:");

        corComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Branco", "Preto", "Azul", "Amarelo", "Verde", "Rosa" }));

        generoLabel.setText("GÊNERO:");

        generoGroup.add(femRadioButton);
        femRadioButton.setText("Feminino");
        femRadioButton.setActionCommand("Feminino");

        generoGroup.add(mascRadioButton);
        mascRadioButton.setText("Masculino");
        mascRadioButton.setActionCommand("Masculino");

        quantidadeLabel.setText("QUANTIDADE:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(vlrUnitarioLabel)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vlrUnitarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(generoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mascRadioButton)
                                .addGap(47, 47, 47)
                                .addComponent(quantidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(descricaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tamanhoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanhoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoLabel)
                    .addComponent(descricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamanhoLabel)
                    .addComponent(tamanhoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corLabel)
                    .addComponent(corComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generoLabel)
                            .addComponent(femRadioButton)
                            .addComponent(mascRadioButton)
                            .addComponent(quantidadeLabel)
                            .addComponent(quantidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vlrUnitarioLabel)
                            .addComponent(vlrUnitarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "TAMANHO", "COR", "GÊNERO", "QUANTIDADE", "VALOR UNITÁRIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow-back-outline-128.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/img_249588.png"))); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit_font_awesome.svg.png"))); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("VOLTAR");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("EDITAR");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SALVAR");

        deleteButtpn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/su__delete_icon_1165018.png"))); // NOI18N
        deleteButtpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtpnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EXCLUIR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteButtpn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteButtpn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        pesquisarLabel.setText("PESQUISAR PRODUTO:");

        pesquisarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTxtActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pesquisarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarLabel)
                    .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("NOVOS PRODUTOS", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
         ArrayList<Produto> linhasProdutos = ProdutoController.Pesquisar(pesquisarTxt.getText());
        
        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("CÓDIGO");
        tmProdutos.addColumn("DESCRIÇÃO");
        tmProdutos.addColumn("TAMANHO");
        tmProdutos.addColumn("COR");
        tmProdutos.addColumn("GÊNERO");
        tmProdutos.addColumn("QUANTIDADE");
        tmProdutos.addColumn("VALOR UNITÁRIO");
        tabelaProduto.setModel(tmProdutos);
        
        for(Produto p:linhasProdutos){
            String[] prod = {String.valueOf(p.getCodigo()), p.getDescricao(), p.getTamanho(), 
            p.getCor(), p.getGenero(), String.valueOf(p.getQtd()), String.valueOf(p.getValorUnitario())};
            tmProdutos.addRow(prod);
        }
        
        tabelaProduto.getColumnModel().getColumn(0).setPreferredWidth(80); //ID
        tabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabelaProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(3).setPreferredWidth(70);
        tabelaProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(6).setPreferredWidth(150);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                
        tabelaProduto.getColumnModel().getColumn(0).setCellRenderer(centralizado); //ID
        tabelaProduto.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(4).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(5).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(6).setCellRenderer(centralizado);
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void pesquisarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarTxtActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        ValidarCampos();
        if(modoTela.equals("Criar")){
            if(ProdutoController.Salvar(descricaoTxt.getText(), tamanhoComboBox.getSelectedItem().toString(), corComboBox.getSelectedItem().toString(), 
                                        generoGroup.getSelection().getActionCommand(), Integer.parseInt(quantidadeTxt.getText()), Double.parseDouble(vlrUnitarioTxt.getText()))){
                
                this.LoadTable();
                JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!");
                LimparFormulario();
            } else{
                JOptionPane.showMessageDialog(null,"Falha ao cadastrar produto!");
            }
        } else{
            if(ProdutoController.Atualizar(descricaoTxt.getText(), tamanhoComboBox.getSelectedItem().toString(), corComboBox.getSelectedItem().toString(), 
                    generoGroup.getSelection().getActionCommand(), Integer.parseInt(quantidadeTxt.getText()), Double.parseDouble(vlrUnitarioTxt.getText()), codProduto)){
                
                this.LoadTable();
                JOptionPane.showMessageDialog(null,"Produto atualizado com sucesso!");
                LimparFormulario();
            } else{
                JOptionPane.showMessageDialog(null,"Falha ao atualizar produto!");
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        modoTela = "Criar";
        HabilitarFormulario();
        
        descricaoTxt.setText("");
        tamanhoComboBox.setSelectedItem("Selecionar...");
        corComboBox.setSelectedItem("Selecionar...");  
        mascRadioButton.setSelected(false);                    
        femRadioButton.setSelected(false);                 
        quantidadeTxt.setText("");
        vlrUnitarioTxt.setText("");
                
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtpnActionPerformed
        // TODO add your handling code here:
        if(tabelaProduto.getRowCount() > 0){
            int numeroLinha = tabelaProduto.getSelectedRow();
            if(ProdutoController.Excluir(Integer.parseInt(tabelaProduto.getValueAt(numeroLinha,0).toString()))){
                this.LoadTable();
                JOptionPane.showMessageDialog(this,"Produto excluído da base de dados");
            }else{
                JOptionPane.showMessageDialog(this,"Falha ao excluir o produto!");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Não há produtos para excluir!");
        }
    }//GEN-LAST:event_deleteButtpnActionPerformed

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        // TODO add your handling code here:
        if(tabelaProduto.getRowCount()>0){
            //Verifico se o usuário selecionou alguma linha (Primeira linha = 0)
            if(tabelaProduto.getSelectedRow()>=0){
                //Variável acessória para identifcar se o formulário está em modo de edição ou alteração
                modoTela = "Editar";

                //Atribuo os valores que estão na linha selecionada para a tabela
                descricaoTxt.setText(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 1).toString());
                tamanhoComboBox.setSelectedItem(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 2).toString());
                corComboBox.setSelectedItem(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 3).toString());
                //TODO: pegar a seleção do genero feminino ou masculino                
                if(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 4).toString().equals("Masculino")){
                   mascRadioButton.setSelected(true); 
                   femRadioButton.setEnabled(false);
                }else{
                    femRadioButton.setSelected(true);
                    mascRadioButton.setEnabled(false);
                }
                quantidadeTxt.setText(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 5).toString());
                vlrUnitarioTxt.setText(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 6).toString());
                codProduto = Integer.parseInt(tabelaProduto.getModel().getValueAt(tabelaProduto.getSelectedRow(), 0).toString());
                
            }
            else{
                JOptionPane.showMessageDialog(this,"Selecione um produto para editar!");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Não há produto para editar!");
        }
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        HabilitarFormulario();        
    }//GEN-LAST:event_editButtonActionPerformed
    
    public void ValidarCampos(){
        javax.swing.JLabel[] vetorLabel = {descricaoLabel, tamanhoLabel, corLabel, generoLabel,
                                           quantidadeLabel, vlrUnitarioLabel};
        
        javax.swing.JTextField[] vetorTxt = {descricaoTxt, vlrUnitarioTxt};
        
        Validador.CamposVazios(vetorTxt, vetorLabel);
    }
    
    public void HabilitarFormulario(){
        descricaoTxt.setEditable(true);
        tamanhoComboBox.setEnabled(true);
        corComboBox.setEnabled(true);
        femRadioButton.setEnabled(true);
        mascRadioButton.setEnabled(true);
        quantidadeTxt.setEnabled(true);
        vlrUnitarioTxt.setEditable(true);
    }

    public void DesabilitarFormulario(){
        descricaoTxt.setEditable(false);
        tamanhoComboBox.setEnabled(false);
        corComboBox.setEnabled(false);
        femRadioButton.setEnabled(false);
        mascRadioButton.setEnabled(false);
        quantidadeTxt.setEnabled(false);
        vlrUnitarioTxt.setEditable(false);
    }
    
    public void BordasTransparentes(){
        descricaoTxt.setBorder(null);
        vlrUnitarioTxt.setBorder(null);
    }
    
    public void LimparFormulario(){
        descricaoTxt.setText("");
        tamanhoComboBox.setSelectedIndex(0);
        corComboBox.setSelectedIndex(0);
        generoGroup.clearSelection();
        quantidadeTxt.setText("");
        vlrUnitarioTxt.setText("");
    }
    
    public void LoadTable(){
        ArrayList<String[]> linhasProdutos = ProdutoController.getProdutos();
        
        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("CÓDIGO");
        tmProdutos.addColumn("DESCRIÇÃO");
        tmProdutos.addColumn("TAMANHO");
        tmProdutos.addColumn("COR");
        tmProdutos.addColumn("GÊNERO");
        tmProdutos.addColumn("QUANTIDADE");
        tmProdutos.addColumn("VALOR UNITÁRIO");
        tabelaProduto.setModel(tmProdutos);
        
        for(String[] p:linhasProdutos){
            tmProdutos.addRow(p);
        }
        
        tabelaProduto.getColumnModel().getColumn(0).setPreferredWidth(80); //ID
        tabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabelaProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(3).setPreferredWidth(70);
        tabelaProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabelaProduto.getColumnModel().getColumn(6).setPreferredWidth(150);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        
        tabelaProduto.getColumnModel().getColumn(0).setCellRenderer(centralizado); //ID
        tabelaProduto.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(4).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(5).setCellRenderer(centralizado);
        tabelaProduto.getColumnModel().getColumn(6).setCellRenderer(centralizado);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> corComboBox;
    private javax.swing.JLabel corLabel;
    private javax.swing.JButton deleteButtpn;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextField descricaoTxt;
    private javax.swing.JButton editButton;
    private javax.swing.JRadioButton femRadioButton;
    private javax.swing.ButtonGroup generoGroup;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton mascRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pesquisarLabel;
    private javax.swing.JTextField pesquisarTxt;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JTextField quantidadeTxt;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JComboBox<String> tamanhoComboBox;
    private javax.swing.JLabel tamanhoLabel;
    private javax.swing.JLabel vlrUnitarioLabel;
    private javax.swing.JTextField vlrUnitarioTxt;
    // End of variables declaration//GEN-END:variables
}
